"""
MCP server for database operations using Oracle DB.
"""

import oracledb
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from dataclasses import dataclass

from mcp.server.fastmcp import Context, FastMCP


@dataclass
class AppContext:
    """Application context with database connection."""
    db: oracledb.Connection


@asynccontextmanager
async def app_lifespan(server: FastMCP) -> AsyncIterator[AppContext]:
    """Manage application lifecycle with database connection."""
    # Oracle connection details
    hostname = "sgxydfg"
    port = 1521
    username = "cash"
    password = "Cash@123"
    service_name = "exsgid"

    # Create connection string
    dsn = oracledb.makedsn(hostname, port, service_name=service_name)
    db = oracledb.connect(user=username, password=password, dsn=dsn)

    # Create sample table if it doesn't exist
    try:
        cursor = db.cursor()
        cursor.execute("""
            CREATE TABLE users (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(100) NOT NULL,
                age NUMBER
            )
        """)
        db.commit()
    except oracledb.DatabaseError as e:
        # Table might already exist, continue
        if "ORA-00955" not in str(e):  # ORA-00955 is "name is already used by an existing object"
            raise

    # Insert sample data if table is empty
    cursor = db.cursor()
    cursor.execute("SELECT COUNT(*) FROM users")
    if cursor.fetchone()[0] == 0:
        cursor.executemany(
            "INSERT INTO users (name, age) VALUES (:1, :2)",
            [("Alice", 30), ("Bob", 25), ("Charlie", 35)]
        )
        db.commit()

    try:
        yield AppContext(db=db)
    finally:
        db.close()


# Create FastMCP server
mcp = FastMCP("Oracle DB Server", lifespan=app_lifespan)


@mcp.tool()
def query_db(query: str, ctx: Context) -> str:
    """Execute a SELECT query on the Oracle database and return results."""
    db = ctx.request_context.lifespan_context.db
    cursor = db.cursor()
    try:
        cursor.execute(query)
        # Get column names
        columns = [desc[0] for desc in cursor.description]
        results = cursor.fetchall()

        if not results:
            return "No results found."

        # Format results as table
        output = []
        # Header
        output.append(" | ".join(columns))
        # Separator
        output.append("-" * (sum(len(col) for col in columns) + len(columns) * 3 - 3))
        # Data rows
        for row in results:
            output.append(" | ".join(str(cell) for cell in row))

        return "\n".join(output)
    except Exception as e:
        return f"Error executing query: {e}"


@mcp.tool()
def execute_db(query: str, ctx: Context) -> str:
    """Execute an INSERT, UPDATE, or DELETE query on the Oracle database."""
    db = ctx.request_context.lifespan_context.db
    cursor = db.cursor()
    try:
        cursor.execute(query)
        db.commit()
        return f"Query executed successfully. Rows affected: {cursor.rowcount}"
    except Exception as e:
        return f"Error executing query: {e}"


@mcp.resource("db://schema")
def get_schema() -> str:
    """Get the Oracle database schema information."""
    return """
Oracle Database Tables:
- users: id (NUMBER PRIMARY KEY), name (VARCHAR2(100)), age (NUMBER)
    """


if __name__ == "__main__":
    mcp.run()