"""
MCP server for database operations using Oracle DB.
"""

import oracledb
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from dataclasses import dataclass
from typing import Optional

from mcp.server.fastmcp import Context, FastMCP


@dataclass
class AppContext:
    """Application context with database connection."""
    db: oracledb.Connection
    driver_type: str = "thin"


def configure_oracle_driver(driver_type: str = "thin") -> None:
    """
    Configure Oracle driver type.

    Args:
        driver_type: Type of Oracle driver to use
            - "thin": Pure Python driver (equivalent to oracle.jdbc.driver.OracleDriver thin)
            - "thick": Requires Oracle Instant Client libraries
    """
    if driver_type == "thin":
        # Use thin driver - pure Python implementation
        # Equivalent to oracle.jdbc.driver.OracleDriver(thin)
        oracledb.init_oracle_client(config_dir=None)
    elif driver_type == "thick":
        # Use thick driver - requires Oracle Instant Client
        oracledb.init_oracle_client()
    else:
        raise ValueError(f"Unsupported driver type: {driver_type}. Use 'thin' or 'thick'.")


def create_oracle_connection(
    hostname: str,
    port: int,
    username: str,
    password: str,
    service_name: str,
    driver_type: str = "thin"
) -> oracledb.Connection:
    """
    Create Oracle database connection with specified driver type.

    Args:
        hostname: Oracle server hostname
        port: Oracle server port
        username: Database username
        password: Database password
        service_name: Oracle service name
        driver_type: Driver type ("thin" or "thick")

    Returns:
        Oracle database connection
    """
    configure_oracle_driver(driver_type)

    # Create DSN (Data Source Name)
    dsn = oracledb.makedsn(hostname, port, service_name=service_name)

    # Connect using specified driver type
    if driver_type == "thin":
        # Thin driver connection (equivalent to JDBC thin driver)
        return oracledb.connect(
            user=username,
            password=password,
            dsn=dsn,
            config_dir=None  # Explicitly use thin driver
        )
    else:
        # Thick driver connection
        return oracledb.connect(
            user=username,
            password=password,
            dsn=dsn
        )


@asynccontextmanager
async def app_lifespan(server: FastMCP) -> AsyncIterator[AppContext]:
    """Manage application lifecycle with database connection."""
    # Oracle connection details
    hostname = "sgxydfg"
    port = 1521
    username = "cash"
    password = "Cash@123"
    service_name = "exsgid"
    driver_type = "thin"  # Use thin driver (equivalent to oracle.jdbc.driver.OracleDriver(thin))

    # Create connection using thin driver
    db = create_oracle_connection(
        hostname=hostname,
        port=port,
        username=username,
        password=password,
        service_name=service_name,
        driver_type=driver_type
    )

    # Create sample table if it doesn't exist
    try:
        cursor = db.cursor()
        cursor.execute("""
            CREATE TABLE users (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(100) NOT NULL,
                age NUMBER
            )
        """)
        db.commit()
    except oracledb.DatabaseError as e:
        # Table might already exist, continue
        if "ORA-00955" not in str(e):  # ORA-00955 is "name is already used by an existing object"
            raise

    # Insert sample data if table is empty
    cursor = db.cursor()
    cursor.execute("SELECT COUNT(*) FROM users")
    if cursor.fetchone()[0] == 0:
        cursor.executemany(
            "INSERT INTO users (name, age) VALUES (:1, :2)",
            [("Alice", 30), ("Bob", 25), ("Charlie", 35)]
        )
        db.commit()

    try:
        yield AppContext(db=db, driver_type=driver_type)
    finally:
        db.close()


# Create FastMCP server
mcp = FastMCP("Oracle DB Server", lifespan=app_lifespan)


def _validate_select_query(query: str) -> Optional[str]:
    """Validate that the query is a SELECT (or WITH) statement.

    Returns:
        None if valid, otherwise an error message.
    """
    if not query or not isinstance(query, str):
        return "Error: Query must be a non-empty string."

    normalized = query.strip().lower()
    if not (normalized.startswith("select") or normalized.startswith("with")):
        return "Error: Only SELECT queries are allowed. DDL/DML statements (INSERT/UPDATE/DELETE/CREATE) are not permitted."

    return None


@mcp.tool()
def query_db(query: str, ctx: Context) -> str:
    """Execute a SELECT query on the Oracle database and return results."""
    validation_error = _validate_select_query(query)
    if validation_error:
        return validation_error

    db = ctx.request_context.lifespan_context.db
    cursor = db.cursor()
    try:
        cursor.execute(query)
        # Get column names
        columns = [desc[0] for desc in cursor.description]
        results = cursor.fetchall()

        if not results:
            return "No results found."

        # Format results as table
        output = []
        # Header
        output.append(" | ".join(columns))
        # Separator
        output.append("-" * (sum(len(col) for col in columns) + len(columns) * 3 - 3))
        # Data rows
        for row in results:
            output.append(" | ".join(str(cell) for cell in row))

        return "\n".join(output)
    except Exception as e:
        return f"Error executing query: {e}"


@mcp.tool()
def execute_db(query: str, ctx: Context) -> str:
    """Reject non-SELECT queries; only SELECT is allowed."""
    validation_error = _validate_select_query(query)
    if validation_error:
        return validation_error

    return "Error: This server only supports SELECT queries. Use 'query_db' for SELECT statements."

@mcp.tool()
def get_driver_info(ctx: Context) -> str:
    """Get information about the current Oracle driver configuration."""
    driver_type = ctx.request_context.lifespan_context.driver_type
    return f"""
Current Oracle Driver Configuration:
- Driver Type: {driver_type}
- Equivalent JDBC Driver: oracle.jdbc.driver.OracleDriver({driver_type})
- Description: {'Pure Python implementation (no Oracle client required)' if driver_type == 'thin' else 'Requires Oracle Instant Client libraries'}
- Connection Method: {'Thin driver (JDBC equivalent)' if driver_type == 'thin' else 'Thick driver (native Oracle client)'}
    """


@mcp.tool()
def switch_driver_type(ctx: Context, new_driver_type: str) -> str:
    """Switch between thin and thick Oracle driver types.

    Note: This requires server restart to take effect.

    Args:
        new_driver_type: Driver type to switch to ("thin" or "thick")
    """
    if new_driver_type not in ["thin", "thick"]:
        return "Error: Invalid driver type. Use 'thin' or 'thick'."

    return f"""
Driver type change requested: {new_driver_type}

Note: To apply this change:
1. Update the driver_type variable in app_lifespan() function
2. Restart the MCP server

Current driver: {ctx.request_context.lifespan_context.driver_type}
Requested driver: {new_driver_type}
Equivalent JDBC: oracle.jdbc.driver.OracleDriver({new_driver_type})
    """


@mcp.resource("db://schema")
def get_schema() -> str:
    """Get the Oracle database schema information."""
    return """
Oracle Database Configuration:
- Driver: oracledb (Python Oracle Database driver)
- Driver Type: thin (equivalent to oracle.jdbc.driver.OracleDriver(thin))
- Connection: Pure Python implementation (no Oracle client required)

Tables:
- users: id (NUMBER PRIMARY KEY), name (VARCHAR2(100)), age (NUMBER)
    """


if __name__ == "__main__":
    mcp.run()